### PR TITLE
feat: new design 

### PR DESCRIPTION
**Pull request by marinogabri**
new design of the main gui elements
Preview:
newDeisgn

### CODE REVIEW

**Comment by JamesEU** [comment]
Hi, I enjoy the rest of the designs. However, the Main menu design doesn't fit for vRP.

**Comment by marinogabri** [comment]
> Hi, I enjoy the rest of the designs. However, the Main menu design doesn't fit for vRP.
Hi! I don’t agree with you because the phone like menu it’s today very outdated and it doesn’t fit with the phone resources used in today servers. Also vRP 1 wasn’t born with this menu style, but that’s your choice and I respect it 🙂

**Comment by kalinzange** [comment]
> > Hi, I enjoy the rest of the designs. However, the Main menu design doesn't fit for vRP.
> 
> Hi! I don’t agree with you because the phone like menu it’s today very outdated and it doesn’t fit with the phone resources used in today servers. Also vRP 1 wasn’t born with this menu style, but that’s your choice and I respect it 🙂

Can agree with marinogabri, I don't see how does the design doesn't fit for vRP meanwhile people are likely to modify or put some HUD from FiveM Forums

**Comment by JamesEU** [comment]
Again, the phone should be kept as an actual phone as this is too similar to the same design as the actual original vRP. THIS is why it does not fit

**Comment by kalinzange** [comment]
> Again, the phone should be kept as an actual phone as this is too similar to the same design as the actual original vRP. THIS is why it does not fit

Saying this, if marinogabri applies the new design to the ticket notification & prompt it is more likely for the PR to be accepted?

**Comment by JamesEU** [comment]
Yes as mentioned

**Comment by marinogabri** [comment]
> Yes as mentioned

If you have no new ideas about the menu I can follow, i will revert the changes made to the to menu so you can merge the pr.

**Comment by JamesEU** [comment]
That's fine as long as you revert the changes made to the menu (phone). You can include this as a separate thing if you'd like within your own repository / Github release.

**Review by JamesEU — CHANGES_REQUESTED** [review]
Remove modifications to the Phone UI then this PR can and will be accepted.

**Comment by marinogabri** [comment]
Mission div also updated

**Review by JamesEU — APPROVED** [review]
After testing and reviewing these new changes they can now be merged.

**Pull request merged**
