### PR TITLE
Update to Blips

### PR DESCRIPTION
**Pull request by kalinzange**
- Moved Blips Folder to /vrp/cfg/blips_markers.lua
- Added Blips Descriptions in /vrp/client/map.lua
- Added Blips Scale in /vrp/client/map.lua
- Added JamesEU PR

### CODE REVIEW

**Review by MM1212 — COMMENTED** [review]
`and not tastoBloccato` where does this come from? vrp/client/gui.lua 154

**Comment by kalinzange** [comment]
> `and not tastoBloccato` where does this come from? vrp/client/gui.lua 154

It was something I was working on but was only for myself, so I've reverted it back

**Comment by MM1212** [comment]
U pushed the same thing again I think xD

**Comment by kalinzange** [comment]
> U pushed the same thing again I think xD

Yeah I did, sorry, should be ok by now. Please let me know any issues

**Pull request merged**
