### PR TITLE
Create setmoney.js

### PR DESCRIPTION
**Pull request by Caz-Developer**
This Should Set The Users Money

### CODE REVIEW

**Review by CallumsAlone — CHANGES_REQUESTED** [review]
This pull request is not correct as on line 7, 8, 9 you have useless variables and useless table query. You clearly copied this from the set group command and did not proof read the code.

**Comment by JamesEU** [comment]
> This pull request is not correct as on line 7, 8, 9 you have useless variables and useless table query. You clearly copied this from the set group command and did not proof read the code.

This is correct.

**Review by JamesEU — CHANGES_REQUESTED** [review]
I'd also like to add that line 10 has an error in fetching the correct UserID and would legit return the string of what would come back from selecting thee UserId. and Params[0] would get the UserId not the amount of money they want.

**Comment by 1Blaze** [comment]
You also have it returning the message of 
return message.reply('Invalid args! Correct term is: ' + process.env.PREFIX + 'addgroup [permid] [amount]')
which is clearly incorrect as it is for setting their money.

**Pull request closed without merging**
