### PR TITLE
Added "getmyid", "getmytempid" chat commands

### PR DESCRIPTION
**Pull request by Caz-Developer**
Added Commands

### CODE REVIEW

**Comment by JamesEU** [comment]
Hello, Caz.

The above code does not account for a user leaving you should store their tempid with their permid so then if they leave the server their permid can still be obtained otherwise this is pretty much useless.

**Comment by Caz-Developer** [comment]
this is just for the client getting there own id ingame, say for admin sits etc, I get what you mean by the temp id storing, ill take that out until I work on an update to store that temporarily while servers are up but delete them when server restarts

**Comment by Caz-Developer** [comment]
on a second note, getmyid is used for the client to get there perm id for say, discord reference, asking people to give money, giving admins your perm id so they can set groups, generally a tool to make admins lives easier

**Comment by JamesEU** [comment]
Also, the brackets are not needed as this is referencing within vRP brackets are only needed for external usage.

**Review by JamesEU — CHANGES_REQUESTED** [review]
Remove brackets from vRP.getUserId

**Review by Caz-Developer — COMMENTED** [review]
made changes

**Review by JamesEU — APPROVED** [review]
Changes are now correct.

**Pull request merged**
